# Generated by Django 3.2.16 on 2023-04-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230405_0158'),
        ('timetable', '0002_auto_20230405_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.user'),
        ),
    ]
